version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1y0gh32a0rw02"
s3_prefix = "lambda-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
